### PR TITLE
v3 upgrade

### PR DESCRIPTION
**Pull request by josephdadams**
converts this module to the new companion v3 api as well as breaks functions into separate files for easier maintenance. Not tested, this is a WIP

### CODE REVIEW

**Comment by josephdadams** [comment]
@murphytodd4 I have started converting this module to the new companion v3 api for you - can you take a look?

**Comment by brenthaag** [comment]
Is there a way I can try this update out? I am trying to get connected to a LynTec and the old module in V3 doesn't work for me (I will try downgrading to V2 and seeing if I can get it to connect, though).

**Comment by josephdadams** [comment]
I don’t remember if it works or not, I got busy with other stuff

**Comment by brenthaag** [comment]
No worries...I just downloaded lastest V2 stable and will try it. I hadn't messed around with Companion until V3, so I'm trying to figure out my connection problem. :)
Thanks.

**Pull request merged**
